Loginpage#5
DSC-University-of-Seoul/raccoon-frontend pull request #23
Opened 2021-02-11 13:03 UTC by min6choi

체크 할 사항 
- import 오류 있는지 

진행 중인 사항 
- 박스 채우기

2021-02-11 17:38 UTC, MOBUMIN commented
styled component를 사용하셨기 때문에 styled-component 패키지 설치하시고 `import styled from "styled-components"` 하셔야합니다! 그 외는 prettier 오류가 나지 않는 이상 괜찮은 것 같습니다.
그런데 이런 import같 은 부분은 실행하면서 error 메시지로 잡아줄거기 때문에 직접 실행해보시는 게 좋을 것 같아요 : )

그런데 커밋 로그가 이렇게 다 뜨는 게 이상한 것 같습니다,, 정확히 어떤 것이 문제다 라고는 할 수 없는데 ... 이대로 merge하면 저희 develop branch 커밋 로그 중복되거나 그러진 않을까요 ? 
위와 같은 문제로 변경사항이 여태 다른 분들이 하셨던 것도 잡혀버려서 민식님이 작성한 코드를 찾기 힘듭니다 ㅠㅠ!

민식님이 현재 DSC 그룹의 repository에서 branch를 파서 PR을 날리셨는데, 저희 협업 방식을 fork후 PR로 확정한 적이 있던가요? 해당 repo에 branch를 파서 PR을 날리는 방식도 가능한지 궁금합니다!

2021-02-11 18:00 UTC, MOBUMIN reviewed
민식님이 slack으로 물어보셨을 때 저는 styled component를 사용 안 했다라고 대답을 했어야했는데, 단순히 import 안했다고 말해버려서 제 말이 오해를 일으킨 것 같아요 ㅠ.ㅠ 민식님은 styled component를 사용하셨기 때문에 styled-component 패키지 설치하시고 import styled from "styled-components" 하셔야합니다! 그 외는 prettier 오류가 나지 않는 이상 괜찮은 것 같습니다.
이런 부분은 실행하면서 error 메시지로 잡아줄거기 때문에 직접 실행해보시는 게 좋을 것 같아요 : )

민식님이 현재 레포의 develop에 바로 커밋한 후에 develop=>main으로 PR 하셨어요...! 저희는 develop과 main 브랜치를 나눠서 나중에 main으로 합치기로 했어요. 그래서 저희는 develop branch로 PR을 날려야 합니다! 바로 커밋하시면 안됩니다 ㅠ.ㅠ 제가 설명을 잘 못해서 ,,, 추가 설명 필요한 부분 있다면 추가 설명 부탁드릴게용 !

민식님이 현재 DSC 그룹의 repository에서 initial setting과 login branch를 파셨는데, 저희 협업 방식을 fork후 PR하기로 확정한 적이 있던가요? 해당 repo에 branch를 파서 PR을 날리는 방식도 가능한지 궁금합니다!

2021-02-11 19:08 UTC, r4k0nb4k0n requested changes
![image](https://user-images.githubusercontent.com/5409746/107684861-a4e9dd80-6ce6-11eb-8c9b-4a25ba38990b.png)
https://github.com/DSC-University-of-Seoul/raccoon-frontend/wiki/CONTRIBUTING
우리 repo의 wiki 페이지에 있는 CONTRIBUTING 가이드를 참고해주세요!

# Request changes

1. `develop` branch로부터 새로운 branch를 파서 commit을 하신 다음 해당 branch에서 `develop` branch로 merge 하는 Pull Request를 날려주세요!
2. 프로젝트 시작부터 scss 파일을 이용해서 스타일을 적용하는 방식을 사용했기 때문에 `styled-components` 모듈도 없어서 `import` 오류가 발생한 것 같네요! 일단 시간이 없기 때문에 scss 방식으로 강제하진 않을게요. `npm install styled-components`로 모듈을 설치하신 다음에 `package.json`을 커밋하시면 됩니다!

2021-02-12 12:06 UTC, min6choi commented
> 민식님이 slack으로 물어보셨을 때 저는 styled component를 사용 안 했다라고 대답을 했어야했는데, 단순히 import 안했다고 말해버려서 제 말이 오해를 일으킨 것 같아요 ㅠ.ㅠ 민식님은 styled component를 사용하셨기 때문에 styled-component 패키지 설치하시고 import styled from "styled-components" 하셔야합니다! 그 외는 prettier 오류가 나지 않는 이상 괜찮은 것 같습니다.
> 이런 부분은 실행하면서 error 메시지로 잡아줄거기 때문에 직접 실행해보시는 게 좋을 것 같아요 : )
> 
> 민식님이 현재 레포의 develop에 바로 커밋한 후에 develop=>main으로 PR 하셨어요...! 저희는 develop과 main 브랜치를 나눠서 나중에 main으로 합치기로 했어요. 그래서 저희는 develop branch로 PR을 날려야 합니다! 바로 커밋하시면 안됩니다 ㅠ.ㅠ 제가 설명을 잘 못해서 ,,, 추가 설명 필요한 부분 있다면 추가 설명 부탁드릴게용 !
> 
> 민식님이 현재 DSC 그룹의 repository에서 initial setting과 login branch를 파셨는데, 저희 협업 방식을 fork후 PR하기로 확정한 적이 있던가요? 해당 repo에 branch를 파서 PR을 날리는 방식도 가능한지 궁금합니다!

형진님이 제가 잘못한 부분에 대한 설명 밑에 해주셔서 일단 styled component 없앤 후 다시 작업하고 올바른 방법으로 PR해보겠습니다 ㅠㅠ

2021-02-12 12:07 UTC, min6choi commented
> ![image](https://user-images.githubusercontent.com/5409746/107684861-a4e9dd80-6ce6-11eb-8c9b-4a25ba38990b.png)
> https://github.com/DSC-University-of-Seoul/raccoon-frontend/wiki/CONTRIBUTING
> 우리 repo의 wiki 페이지에 있는 CONTRIBUTING 가이드를 참고해주세요!
> 
> # Request changes
> 1. `develop` branch로부터 새로운 branch를 파서 commit을 하신 다음 해당 branch에서 `develop` branch로 merge 하는 Pull Request를 날려주세요!
> 2. 프로젝트 시작부터 scss 파일을 이용해서 스타일을 적용하는 방식을 사용했기 때문에 `styled-components` 모듈도 없어서 `import` 오류가 발생한 것 같네요! 일단 시간이 없기 때문에 scss 방식으로 강제하진 않을게요. `npm install styled-components`로 모듈을 설치하신 다음에 `package.json`을 커밋하시면 됩니다!

wiki페이지는 오늘 처음 봤네요 ㅠㅠ 알려주신 방법대로 다시 하고, styled도 scss 적용 후 다시 pr하겠습니다!

2021-02-21 08:39 UTC, closed without merging